### ISSUE TITLE
Longest Mountain in Array- Complexity O(N)

### ISSUE THREAD

**Issue by riyasingh775** [vijaygupta18/Hacktoberfest-2021#137]
**Description:**
An array arr is a mountain array if and only if:
- arr.length >= 3
- There exists some index i (0-indexed) with 0 < i < arr.length - 1 such that:
          - arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
          - arr[i] > arr[i + 1] > ... > arr[arr.length - 1]

Given an integer array arr, return the length of the longest subarray, which is a mountain. Return 0 if there is no mountain subarray.

Example-
Input: arr = [2,1,4,7,3,2,5]

Output: 5

Explanation: The largest mountain is [1,4,7,3,2] which has length 5.

**Comment by riyasingh775** [comment]
I have done PR with time complexity O(N). Please check it!

**Comment by vijaygupta18** [comment]
> I have done PR with time complexity O(N). Please check it!

done
