### ISSUE TITLE
Make sure your PR is valid.

### ISSUE THREAD

**Issue by vijaygupta18** [vijaygupta18/Hacktoberfest-2021#19]
You can Create PR for any project or work... only the condition is it should be yours.

**Comment by raktim00** [comment]
@vijaygupta18 accept my PR #51

**Comment by Karthik-59** [comment]
@vijaygupta18 can you accept my or no.84 bro ?

**Comment by vijaygupta18** [comment]
> @vijaygupta18 can you accept my pr no.84 bro ?

sure
