### ISSUE TITLE
Key Pad Problem [Asked in FAANG Interview]

### ISSUE THREAD

**Issue by aastha01chauhan** [vijaygupta18/Hacktoberfest-2021#214]
I want to contribute for this problem. Please assign this issue to me.

**Comment by Arihant2001** [comment]
i want to do it in c++. plz assign this to me

**Comment by vijaygupta18** [comment]
> I want to contribute for this problem. Please assign this issue to me.

Okay do Pr

**Comment by vijaygupta18** [comment]
> i want to do it in c++. plz assign this to me

Create a seperate folder for c++ and create pr
