### ISSUE TITLE
Subarray with 0 sum- Complexity O(n)

### ISSUE THREAD

**Issue by riyasingh775** [vijaygupta18/Hacktoberfest-2021#215]
Given an array of integers arr,  print Yes or No depending upon whether there is a subarray present with 0-sum or not.

A subarray is a contiguous subsequence of the array.

Example :
Input:
5
4 2 -3 1 6

Output: 
Yes

Explanation: 
2, -3, 1 is the subarray with sum 0.

**Comment by riyasingh775** [comment]
@vijaygupta18 I have done PR. Please review it!

**Comment by HarshS1611** [comment]
![image](https://user-images.githubusercontent.com/81004813/135743869-6dbccabb-05f4-43f7-a5d7-1d360747ac50.png)
I have done this program in java kindly review it
