### ISSUE TITLE
Can you please label my PR #200 as hacktoberfest-accepted?

### ISSUE THREAD

**Issue by AdityaSawant21** [vijaygupta18/Hacktoberfest-2021#244]
Can you please label this PR #200 as hacktoberfest-accepted?

_Originally posted by @AdityaSawant21 in https://github.com/vijaygupta18/Hacktoberfest-2021/issues/200#issuecomment-932913330_

**Comment by AdityaSawant21** [comment]
I will remove this issue but @vijaygupta18 can you please label my PR[#200] as hacktoberfest-accepted  🙏

**Comment by vijaygupta18** [comment]
> I will close this issue but @vijaygupta18 can you please label my PR[#200] as hacktoberfest-accepted 🙏

Don't worry about it.This repo is already marked as Hactoberfest accepted and participating you just have to get your pr merged.

**Comment by AdityaSawant21** [comment]
ok now got it Thanks
