### ISSUE TITLE
Key logger using Python

### ISSUE THREAD

**Issue by Prajwol-Shrestha** [vijaygupta18/Hacktoberfest-2021#279]
Hey! @vijaygupta18 , I would like to contribute a key logger program made using Python.
Please assign it to me.

**Comment by gargi111** [comment]
hey! please assign this issue to me.#hacktoberfest

**Comment by vijaygupta18** [comment]
> Hey! @vijaygupta18 , I would like to contribute a key logger program made using Python. Please assign it to me.

okay create a pr

**Comment by vijaygupta18** [comment]
@gargi111  create pr after verification I'll merge it
