### ISSUE TITLE
Predict Future Sales using Machine Learning

### ISSUE THREAD

**Issue by harshita9621** [vijaygupta18/Hacktoberfest-2021#313]
1. Let's visualize the time-series elements of the data to understand the patterns.
2. The input dimension of the model learned with Train data should be well thought out and predicted with Test data.
3. The task is to forecast the total amount of products sold in every shop for the test set. Note that the list of shops and products slightly changes every month. Creating a robust model that can handle such situations is part of the challenge.

Dataset:
https://www.kaggle.com/c/competitive-data-science-predict-future-sales/data

Assign me this issue under Hacktoberfest'21.

**Comment by vijaygupta18** [comment]
> 1. Let's visualize the time-series elements of the data to understand the patterns.
> 2. The input dimension of the model learned with Train data should be well thought out and predicted with Test data.
> 3. The task is to forecast the total amount of products sold in every shop for the test set. Note that the list of shops and products slightly changes every month. Creating a robust model that can handle such situations is part of the challenge.
> 
> Dataset: https://www.kaggle.com/c/competitive-data-science-predict-future-sales/data
> 
> Assign me this issue under Hacktoberfest'21.

Okay Create a Pr I'll merge it after verification.

**Comment by harshita9621** [comment]
Why this issue are closed

**Comment by vijaygupta18** [comment]
> Why this issue are closed

**Comment by vijaygupta18** [comment]
> Why this issue are closed

let me know when you create your pr.

**Comment by harshita9621** [comment]
> > Why this issue are closed
> 
> let me know when you create your pr.

**Comment by harshita9621** [comment]
tody
