### ISSUE TITLE
Merge two sorted linked lists

### ISSUE THREAD

**Issue by Nithish2032** [vijaygupta18/Hacktoberfest-2021#4]
Hey, I want to add a program that merges two sorted linked lists into one. Please assign me this issue for hacktoberfest 2021.

**Comment by vijaygupta18** [comment]
> Hey, I want to add a program that merges two sorted linked lists into one. Please assign me this issue for hacktoberfest 2021.

okay do PR on this repo

**Comment by sid-khuntwal** [comment]
I have a program a sort of game in cpp, Its a guessing game. Please sign me this issue for hacktoberfest 21

**Comment by ronniepratap** [comment]
> I have a program a sort of game in cpp, Its a guessing game. Please sign me this issue for hacktoberfest 21

Do Pr I'll merge it

**Comment by vijaygupta18** [comment]
> I have a program a sort of game in cpp, Its a guessing game. Please sign me this issue for hacktoberfest 21

Okay Follow the steps mentioned in readme file and generate a PR I'll approve it.

**Comment by sid-khuntwal** [comment]
ok

**Comment by sid-khuntwal** [comment]
Done!

**Comment by Devansh-gaur-1611** [comment]
Can I do the problem using java or is it necessary to do with c++

**Comment by vijaygupta18** [comment]
> Can I do the problem using java or is it necessary to do with c++

You can do in any language.

**Comment by a-n-a-s-s** [comment]
Bro how to make a contributing repo

**Comment by drishyadamodaran** [comment]
Can I do it?

**Comment by vijaygupta18** [comment]
> Bro how to make a contributing repo

follow the readme file instructions...you can contribute anything.

**Comment by vijaygupta18** [comment]
ko

> Can I do it?

Give PR I'll approve it

**Comment by vijaygupta18** [comment]
> > ko
> > > Can I do it?
> > 
> > 
> > Give PR I'll approve it
> 
> done. check now

approved

**Comment by Karthik-59** [comment]
Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?

**Comment by vijaygupta18** [comment]
> Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?

Yeah sure

**Comment by Karthik-59** [comment]
> > Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?
> 
> Yeah sure

Bro, in git push origin <branch-name> command what should be the branch name bro ? Is it the one I created or "main" ? While I am using the (branch-name) created by me (portfolio_branch) error is coming (origin is not appeared ... in git repo"

**Comment by vijaygupta18** [comment]
> > > Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?
> > 
> > 
> > Yeah sure
> 
> Bro, in git push origin command what should be the branch name bro ? Is it the one I created or "main" ? While I am using the (branch-name) created by me (portfolio_branch) error is coming (origin is not appeared ... in git repo"

it should be your branch name...you can try pr using the GitHub page..fork the repo..add your content..and then click on the contribute option... you'll automatically get option for creating pull request.

**Comment by Karthik-59** [comment]
> > > > Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?
> > > 
> > > 
> > > Yeah sure
> > 
> > 
> > Bro, in git push origin command what should be the branch name bro ? Is it the one I created or "main" ? While I am using the (branch-name) created by me (portfolio_branch) error is coming (origin is not appeared ... in git repo"
> 
> it should be your branch name...you can try pr using the GitHub page..fork the repo..add your content..and then click on the contribute option... you'll automatically get option for creating pull request.

Yeah bro ! I got the option to compare and pull request but, it is showing there is nothing to compare.

**Comment by vijaygupta18** [comment]
> > > > > Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?
> > > > 
> > > > 
> > > > Yeah sure
> > > 
> > > 
> > > Bro, in git push origin command what should be the branch name bro ? Is it the one I created or "main" ? While I am using the (branch-name) created by me (portfolio_branch) error is coming (origin is not appeared ... in git repo"
> > 
> > 
> > it should be your branch name...you can try pr using the GitHub page..fork the repo..add your content..and then click on the contribute option... you'll automatically get option for creating pull request.
> 
> Yeah bro ! I got the option to compare and pull request but, it is showing there is nothing to compare.

Then there might be some error.. delete the repo try again..let me know if you get the same error.

**Comment by Karthik-59** [comment]
> > > > > > Hey bro ! I wanna contribute my portfolio project, which is made by html-css-bootstrap, can I do it ?
> > > > > 
> > > > > 
> > > > > Yeah sure
> > > > 
> > > > 
> > > > Bro, in git push origin command what should be the branch name bro ? Is it the one I created or "main" ? While I am using the (branch-name) created by me (portfolio_branch) error is coming (origin is not appeared ... in git repo"
> > > 
> > > 
> > > it should be your branch name...you can try pr using the GitHub page..fork the repo..add your content..and then click on the contribute option... you'll automatically get option for creating pull request.
> > 
> > 
> > Yeah bro ! I got the option to compare and pull request but, it is showing there is nothing to compare.
> 
> Then there might be some error.. delete the repo try again..let me know if you get the same error.

okay bro !

**Comment by deenu-1001** [comment]
can you assign this to me?

**Comment by Mr-vabs** [comment]
Hello , can I add some linked list , sorting algorithms and 2D matrix operations ( sum of rows columns and all ) and tree traversal program into this repo?

**Comment by vijaygupta18** [comment]
> Hello , can I add some linked list , sorting algorithms and 2D matrix operations ( sum of rows columns and all ) and tree traversal program into this repo?

yes you can add
