### ISSUE TITLE
Exploratory Data Analysis 

### ISSUE THREAD

**Issue by ankit-kmar** [vijaygupta18/Hacktoberfest-2021#95]
Exploratory data analysis on the set of data. Carried out using libraries like pandas, numpy, seaborn and matplotlib

**Comment by ankit-kmar** [comment]
pls assign this issue to me! @vijaygupta18

**Comment by vijaygupta18** [comment]
Congratulations for your Open source contribution. Don't forget to add a star on this repo.. Happy hacking

**Comment by vijaygupta18** [comment]
> pls assign this issue to me! @vijaygupta18

sure .. generate pr
